apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-2replica
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  dataEngine: "v1"
  dataLocality: "disabled"
  disableRevisionCounter: "true"
  fsType: "ext4"
  staleReplicaTimeout: "30"
