---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: bc3b7339-0bfe-4b97-92b0-4c8e3e56a61f
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true

    ingress:
      # Route ALL traffic to ingress-nginx (it handles hostname routing)
      - service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
        originRequest:
          noTLSVerify: true
