apiVersion: v1
kind: Secret
metadata:
    name: wazuh-credentials
    namespace: wazuh
type: Opaque
stringData:
    indexer-admin-password: ENC[AES256_GCM,data:ha2oJ8x4S6ARhRgimKw=,iv:Px79Zt/M4wVzUZGx3WS/s8igCWVk8FhfSaKjQK1D1jU=,tag:Xs7ZLK3n4Md1cETjYL5LFg==,type:str]
    api-username: ENC[AES256_GCM,data:iuIAzLPnL1kO,iv:lBVGzfLCKFqAjv/Uq8zL6kPvuFOnHvDpBrDhPOHWEX0=,tag:REtErSFULlqsruHYpUftSA==,type:str]
    api-password: ENC[AES256_GCM,data:J2dBfkvpkw+Bz+9aWOgg5A==,iv:Q9OIYXa34yt6MSIzG0rDt1BQt7A4T+72A3t1bCspwak=,tag:j1UW0sMyKtupa5hjQ7v/qQ==,type:str]
    dashboard-username: ENC[AES256_GCM,data:km09r7/ZsUY158R/,iv:c3rqgtNSiQoXhPTMkdfbl6y29rDJ2lNWdtOxK7RBCs8=,tag:7XxUdNhCfsJKdSpT1RxVCA==,type:str]
    dashboard-password: ENC[AES256_GCM,data:NnfFHGteApAMFn22,iv:VmzrJgA3udE/Iq6hxvZunrgFswWTevps+Vj9RoHLPmk=,tag:RU21A0ECdIFCR4TKJOwtBw==,type:str]
    ntfy-username: ENC[AES256_GCM,data:XiVw+t8tKW+3CN+VSNTg2Tc=,iv:VospNHZYbr8cgnRn1le5c3uuK8ENqkboyxcqL7mm8xA=,tag:m+dxOuOGpqfxpMufjEq44g==,type:str]
    ntfy-password: ENC[AES256_GCM,data:sAzOOznhrAIxbnqX+PVFuyqxnFRqG2MaMZzcsU60eDE=,iv:/GKjj+Rw3unfnuOhh1TYJY9qJrFPFxnL2E1UEqhoXvo=,tag:8N9TXMIP1jJAVa2vee442A==,type:str]
sops:
    age:
        - recipient: age1kwpf29n6naudjyjyrxxz0mu9j07xcp3waa0juandxqzd858scv3qtlymvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZlhZa3JjcEpldHBkVEMx
            d1V5WHhyUjdXc3VQSEV2dlhDc3FNSnUyaVUwCkVaQ01KdjcyWG54YUwvYnFiYlV5
            WlZJMWJERnc2R0xvWVJCVklGSFF2UFkKLS0tIGZISVBpa05ZWWlKZGRLRTB1T3ZQ
            N1JYeHRMa0lzWjR0Wkp0WlA2OEpadW8K5vvojiTO5fDuKB8lDxQSXrhq6LoRqUw0
            jlpGExa17YGZ01R5TKghmbNMt+LrsXGuudVr9J/OEGB6rGWU9XwGdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T17:23:02Z"
    mac: ENC[AES256_GCM,data:qwU1cEVrUlLVvp3zn5dsSuZH1LzIoh6iRVpvj30QvRWg/2QSaJclrqJMPLi7cWAIR/ZX6Rj7Hh7MwInAL02iXgeZVWN9hbgbiQpVvNx5jj8sPkwp3z008KTs344Os8N1kvVNQAM6Gk/tN+rnGKuZNsOHEMRgmX9M02+tVN9x6AE=,iv:Z73UV5SUCsGhtqvdbpab4F10+DbSZdNC3ursSoMQnNU=,tag:aOxKpGpetx0L1WTN2nOpjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
