apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
  namespace: tailscale-ingress
data:
  Corefile: |
    enigmata.local:53 {
        bind 100.89.213.85
        template IN A enigmata.local {
            answer "{{ .Name }} 60 IN A 100.89.213.85"
        }
        template IN AAAA enigmata.local {
            rcode NXDOMAIN
        }
        errors
        cache 300
        log
    }
