apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cronjob.yaml

configMapGenerator:
  - name: deriv-auto-trader-script
    namespace: deriv-trading-bot
    files:
      - deriv-auto-trade.py

generatorOptions:
  disableNameSuffixHash: true
