apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deriv-trading-bot-data
  namespace: deriv-trading-bot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
