apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:lQJVEJbrnwTVokPB4Op9dJg=,iv:9f777PyBhhMJclpiGwJgHxu8EM/PZGfsTDkGgLKqyfY=,tag:RNWxGfZYwbfDbI56Jd5EEg==,type:str]
    client_secret: ENC[AES256_GCM,data:tR956wuuxKnZrE2HwVSTomh9+pFQ52Chm10SPr/i/6pIWHDBpljv0D365DpMb7RzUfYpOyDlJLKFKDvTDxr/,iv:HOGUvepGh1XGux4ww3x1MaE/9paHlegbp5q5WcX8dTk=,tag:tLlNVQn7GOPJqx3rfbjVzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRGdKYUN2QUdPd0oyVDc0
            TjVSc2ExVDNiMmtxclRGQXhEUWVndUhCVlRFCmxrOWZxVE45ZVd3YU1DYkVaQ05M
            T2ZidXJjMnpBYVNGYUh1ZUQwZnN6UlUKLS0tIFpzcHBXT2F4RExnWXJhMG1kL1JC
            UFpWdHRnK0xxODNYM0c4Z1RkU1laSHcK4W7YHrt+QwsPYOw82u8LJ9LqaDyjLXNH
            Xfkb0EIMXuevlsofZQaaNWSg0WLV1uCrg9UJumS0tIpdLpYEPVGC/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kwpf29n6naudjyjyrxxz0mu9j07xcp3waa0juandxqzd858scv3qtlymvp
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-12T02:04:44Z"
    mac: ENC[AES256_GCM,data:h53QzDvP+g034EVKV53VKu6cKJKVwBrGfItxEd2fGtRiIaJJoPINu1ajIjhSu+7UYrYtVx/KJ8TttVRUea7WXltEel/fo3z14ti/e0gHElxkmGVD0TRX2VHnRFKubNirRPjSKSewu/XfGgtz4rKE3lSDPT+D+w5Y1nRvgCtV37Y=,iv:xnlpi2R+KH9rgoLEJC5oCEu5naV6qfCJSYqpik/gxGQ=,tag:uxfDh6uqePLODh7Rqe5+RQ==,type:str]
    version: 3.13.1
